### ISSUE TITLE
How to change the line length preference for warnings in Diagnostics?

### ISSUE THREAD

**Issue by Kabouik** [REditorSupport/atom-ide-r#3]
It seems this package ignores the Atom preferences for preferred line length and max line length (in Settings/Editor), and I still get warnings from atom-ide-ui for all lines that exceed 80 characters despite setting the preference to 160 in Atom settings and all r-related packages (Rbox, Hydrogen, _etc._).

![screenshot from 2018-03-21 14 30 12](https://user-images.githubusercontent.com/7107523/37712987-d65ec98e-2d15-11e8-974b-2b507019c013.png)

Is there a way to change that? My scripts are cluttered with line length warnings, and I don't want to hide warnings because they can be useful for other formatting issues. 

Or is it something set independently from atom-ide-r, like in atom-ide-ui?

**Comment by randy3k** [comment]
Thank you for raising it up. The warnings are generated by [lintr](https://github.com/jimhester/lintr).
Until it is properly addressed in `atom-ide-r`, you could use [.lintr](https://github.com/jimhester/lintr#project-configuration) to manually configure its settings. Ideally, `atom-ide-r` should send the margin information from atom to lintr automatically.

**Comment by randy3k** [comment]
You will probably be okay to uninstall `lintr`, but my suggestion is to configure it properly. Are you writing an R package or just R scripts?

If you writing an R package, just place the following in file `.lintr` under the root directory of your package. 
```r
linters: with_defaults(line_length_linter=line_length_linter(100))
```
If you are writing R scripts, just package the file under the same directory.

**Comment by randy3k** [comment]
If you install the dev version of lintr, you could place the `.lintr` file in your home dirrectory.

```
devtools::install_github("jimhester/lintr")
```

**Comment by Kabouik** [comment]
Thanks, that'll be perfect until this is addressed through  `atom-ide-r`!

**Comment by randy3k** [comment]
You could now also use the [this settings](https://github.com/REditorSupport/languageserver#diagnostics-settings)

**Comment by Kabouik** [comment]
Thanks!

**Comment by Kabouik** [comment]
The link you provided for _languageserver_ now just points to the main page, there is no "Diagonistic settings*  header anymore. Could you please explain how this has to be set up to adjust the line length warnings in Atom for R scripts? For some reason, the _linter_ (or _lintr_? I admit I am confused) warnings in Atom are back for every line above 120 characters, despite my `~/.lintr` file specifying 160 as the limit.

I am totally confused as to which packages I should install in Atom and R to have the warnings. I have installed _linter-lintr_ and _linter_ in Atom, but I don't know if it is necessary or redundant with _atom-ide-r_.

**Comment by randy3k** [comment]
The setting is deprecated in favor the `.lintr` file of the [lintr](https://cran.r-project.org/web/packages/lintr/index.html) package. (Make sure you have the latest version)

You should also remove whatever other atom packages that you have installed. They will get confused.

**Comment by Kabouik** [comment]
Thank you, I will try updating lintr in R and disabling Atom packages linter and linter-lintr.
